In [1]:
import numpy as np
import pandas as pd
import seaborn as sb
import pickle
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split,GridSearchCV
%matplotlib inline
 


In [2]:
df=pd.read_csv('heart.csv')
df.head(5)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [8]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [9]:
df.corr()
x=df.drop(['target'],axis=1)
y=df['target']

In [8]:
#split data into target and feature data
X=df.iloc[:,:-1].values
Y=df.iloc[:,-1].values
print(type(X))

<class 'numpy.ndarray'>


In [10]:
#split the target data into 75% training and 25% testing
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,train_size=0.2,random_state=42)

In [12]:
#normalizing the data or feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)


In [13]:
lr=LogisticRegression()
lr.fit(X_train,Y_train)
lr.score(X_test,Y_test)

0.8256097560975609

In [19]:
yp=lr.predict(X_test)
c=confusion_matrix(Y_test,yp)

In [20]:
c

array([[314,  86],
       [ 57, 363]], dtype=int64)

In [5]:
sv=SVC()
sv.fit(X_train,Y_train)
sv.score(X_test,Y_test)

NameError: name 'X_train' is not defined

In [14]:
rfc=RandomForestClassifier(n_estimators=200)
rfc.fit(X_train,Y_train)
rfc.score(X_test,Y_test)


0.8548780487804878

In [15]:
from sklearn.model_selection import cross_val_score
rfm=cross_val_score(rfc,X_train,Y_train,cv=10)

In [16]:
rfm.mean()

0.896904761904762

In [31]:
from sklearn.neighbors import KNeighborsClassifier
kn=KNeighborsClassifier(n_neighbors=5)
kn.fit(X_train,Y_train)
kn.score(X_test,Y_test)


0.8353658536585366

In [23]:
x=np.array([[58., 100., 248., 122.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  2.]])
print(x[0])
rfc.predict(x)


[ 58. 100. 248. 122.   1.   0.   0.   0.   0.   0.   1.   0.   2.]


array([1], dtype=int64)

In [34]:
pickle.dump(rfc,open('heart.pkl','wb'))